#!/bin/bash
# Helper script to generate client docker run command from JSON config

CONFIG_FILE="${1:-}"
SERVER_ADDR="${2:-}"

if [ -z "${CONFIG_FILE}" ] || [ ! -f "${CONFIG_FILE}" ]; then
    echo "Usage: $0 <config.json> <server_address>"
    echo "  config.json: Generated by generate-tunnel-config.sh"
    echo "  server_address: Public IP or hostname of your SSH server"
    exit 1
fi

if [ -z "${SERVER_ADDR}" ]; then
    echo "Error: Server address is required"
    exit 1
fi

SSH_KEY_BASE64=$(jq -r '.client.ssh_key_base64' "${CONFIG_FILE}")
TUNNEL_ID=$(jq -r '.tunnel_id' "${CONFIG_FILE}")

echo "Generated docker run command for tunnel: ${TUNNEL_ID}"
echo
echo "docker run -d \\"
echo "  --name ssh-tunnel-client \\"
echo "  -e REMOTE_ADDR=${SERVER_ADDR} \\"
echo "  -e SERVER_PORT=2222 \\"
echo "  -e LOCAL_PORT=8080 \\"
echo "  -e REMOTE_PORT=8080 \\"
echo "  -e SSH_KEY_BASE64=\"${SSH_KEY_BASE64}\" \\"
echo "  --restart unless-stopped \\"
echo "  ssh-tunnel-client:latest"
echo
echo "# Or using docker compose with environment file:"
echo
echo "cat > tunnel-client.env << EOF"
echo "REMOTE_ADDR=${SERVER_ADDR}"
echo "SERVER_PORT=2222"
echo "LOCAL_PORT=8080"
echo "REMOTE_PORT=8080"
echo "SSH_KEY_BASE64=${SSH_KEY_BASE64}"
echo "EOF"
echo
echo "docker-compose -f docker-compose.client.yml up -d"
